version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        volumes:
            - ../:/var/www/html
        environment:
            - DB_HOST="laravel-db"
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=mysql
            - DB_PASSWORD=mysqlpass
        depends_on:
            - db
        networks:
            - laravel-network

    db:
        image: mysql:8.0
        container_name: laravel-db
        restart: unless-stopped
        tty: true
        ports:
            - "3309:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysqlpass
            MYSQL_ROOT_PASSWORD: root
        networks:
            - laravel-network

    web:
        image: nginx:1.21-alpine
        container_name: laravel-web
        restart: unless-stopped
        ports:
            - "8011:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ../:/var/www/html
        depends_on:
            - app
        networks:
            - laravel-network
    redis:
        image: redis:alpine
        container_name: laravel-redis
        restart: unless-stopped
        ports:
            - "6380:6379"
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge
